### ISSUE TITLE
Enquiry 

### ISSUE THREAD

**Issue by MYMBECKY** [0xTCG/aldy#51]
May I ask the following, I've read the Nature and BioRxiv paper and have the following questions: 
1. Could we use exome instead of genome sequencing data in BAM format?
2. Output file will be in star-allele nomenclature (with major and minor alleles), correct? 
3. Will variant specific guideline be available in the output or one needs to refer to indiviual variant guideline in CPIC? 
4. Is downloading and using the software free for research purpose? 
Thank you very much!

**Comment by inumanag** [comment]
Hi @MYMBECKY 

1. Yes, you can. However, note the limitations: no CN support for CYP2A6/2D6 and some alleles cannot be detected because their key SNPs are not sequenced.
2. Yes.
3. Aldy will output allele-level guidelines (when available). However, for any real clinical work, please do consult CPIC. We just scrape the existing databases to provide this information; it is very limited as of now and no clinical guarantees can be made for its accuracy.
4. Yes!
