### ISSUE TITLE
Incorrect label for CYP2E1*7.005?

### ISSUE THREAD

**Issue by ldgauthier** [0xTCG/aldy#62]
I was looking through the allele definitions for CYP2E1 and I believe the label for one of the suballeles is incorrect.  The label for CYPE2E1*7.005 is the same as for CYP2E1*7.004, but the first SNP is not the same as for the *7A allele:

CYP2E1*7.005:
    label: CYP2E1*7A_1B
    mutations:
    - [4963, G>T, rs6413420, 5'UTR]
    - [15271, G>C, rs2070676]

Can someone double check this or explain it to me?

**Comment by inumanag** [comment]
Hi @ldgauthier 

This is an amalgamation of 7A and 1B alleles (hence the label `CYP2E1*7A_1B `). Any name that has `_` in it is an amalgamation. IIRC this entry got in via Pharmacoscan that had support for this allele. If you think it is wrong (it could be), please let me know (or you can just disable it by commenting out those lines in the YML file).

**Comment by ldgauthier** [comment]
Specifically I was surprised that CYP2E1*7.004 and CYP2E1*7.005 have the same label -- are labels not unique?

**Comment by inumanag** [comment]
This one is bit open to interpretation: both share \*7 key SNPs and thus _could_ be considered as variants of \*7 (happens all the time with other genes). Again, this might not necessarily hold; that's why Aldy reports label as well (e.g., 7A_1B) to indicate that there is an amalgamation. You can change the database ID to make it more visible if you prefer.
